baseURL: https://masum.me
title: The 8-bit Brain
theme: PaperMod
paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: "G-LTR5L2PYKX"

minify:
  disableXML: true
#  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

languages:
  en:
    contentDir: content/en
    languageName: English
    weight: 1
    DateFormat: "January 2, 2006"
    profileMode:
      enabled: true
      imageUrl: "image/profile_avatar.webp"
      imageWidth: 150
      imageHeight: 150
      title: Masumul Hassan
      subtitle: Software Engineer | Security Enthusiasts | DevOps
      buttons:
        - name: Posts
          url: posts
        - name: Projects
          url: projects
    menu:
      main:
        - identifier: search
          name: Search
          url: /search/
          weight: 4
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 3
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 4
        - identifier: about
          name: About
          url: /about/
          weight: 5

params:
  env: production
  title: The 8-bit Brain
  description: Consume -> Process -> Store
  keywords: [ Blog ]
  author: Masumul Hassan
  images: [ "https://images.unsplash.com/photo-1510843572979-e4b9e790fdd7?auto=format&fit=crop&w=720&q=80" ]

  defaultTheme: auto # dark, light
  disableThemeToggle: false
  displayFullLangName: true

  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    favicon: "/favicon.ico"

  socialIcons:
    - name: github
      url: "https://github.com/masumulhassan"
    - name: linkedin
      url: "https://www.linkedin.com/in/masumul-hassan/"
    - name: twitter
      url: "https://twitter.com/masumulhassan1"
    - name: email
      url: "mailto:contact@masum.me"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]

taxonomies:
  tag: tags
  
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
